title: Alexis Catnip # your name (or website title) here
logo: "https://avatars.githubusercontent.com/u/42345054?v=4" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software engineer with 1 year of professional experience.   
  <br><br>
  I like cats. I am not a cat.
  <br><br>
  The profile pic is probably stolen from somewhere on the internets. I would remove it if you contact me. 
  <br><br>

  <a href="https://sg.linkedin.com/in/alexis-khoo-6198a2199">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
