title: Alexis Catnip # your name (or website title) here
logo: "https://avatars.githubusercontent.com/u/42345054?v=4" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Programmer.
  <br><br>
  Interested in virtual worlds, robotics, and the C# programming language.
  <br><br>
  <i> "the simulacrum precedes the real" </i>
  <br><br>
  
  <a href="https://sg.linkedin.com/in/alexis-khoo-6198a2199">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
remote_theme: zivhub/monophase@main
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
plugins:
  - jekyll-remote-theme
